// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpVtW_Jcr0EtY_cz3FG0P3EPggZBo6YHY',
    appId: '1:123108522841:web:cb5dcc393a3e1552c2ea48',
    messagingSenderId: '123108522841',
    projectId: 'smartplacement-3b3cc',
    authDomain: 'smartplacement-3b3cc.firebaseapp.com',
    storageBucket: 'smartplacement-3b3cc.firebasestorage.app',
    measurementId: 'G-KLMEC7C72T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_l4x1zMTIeijqyr0UC3QiU5bGfAViv9M',
    appId: '1:123108522841:android:2b18f18c4c5cca94c2ea48',
    messagingSenderId: '123108522841',
    projectId: 'smartplacement-3b3cc',
    storageBucket: 'smartplacement-3b3cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IB2kOGLWqCTXV2lne-H0OrSD868h-TA',
    appId: '1:123108522841:ios:b61fac43e336e71bc2ea48',
    messagingSenderId: '123108522841',
    projectId: 'smartplacement-3b3cc',
    storageBucket: 'smartplacement-3b3cc.firebasestorage.app',
    iosBundleId: 'com.example.smartPlacement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3IB2kOGLWqCTXV2lne-H0OrSD868h-TA',
    appId: '1:123108522841:ios:b61fac43e336e71bc2ea48',
    messagingSenderId: '123108522841',
    projectId: 'smartplacement-3b3cc',
    storageBucket: 'smartplacement-3b3cc.firebasestorage.app',
    iosBundleId: 'com.example.smartPlacement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpVtW_Jcr0EtY_cz3FG0P3EPggZBo6YHY',
    appId: '1:123108522841:web:09efc51bda5ffb00c2ea48',
    messagingSenderId: '123108522841',
    projectId: 'smartplacement-3b3cc',
    authDomain: 'smartplacement-3b3cc.firebaseapp.com',
    storageBucket: 'smartplacement-3b3cc.firebasestorage.app',
    measurementId: 'G-2L5M3CDKL4',
  );
}
